services:
  postgres:
    image: postgres:13.12
    restart: always
    ports:
      - 5432:5432
    networks: [dentist]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  app:
    build: .
    command: "bundler exec rails server -b 0.0.0.0"
    ports:
      - 3000:3000
    networks: [dentist]
    depends_on:
      - postgres
    links:
      - postgres

networks:
  dentist:
    driver: bridge